### ISSUE TITLE
Docker image 9-minimal restarting

### ISSUE THREAD

**Issue by perry-amsterdam** [AlmaLinux/docker-images#61]
Hi i have a couple of almalinux containers running version 8, that works.
When is try it with version 9, it keeps restarting without log output.
I use the following docker-compose file for test.
Why is it restarting ?

Greeting from Amsterdam :-),
Perry

version: '3.1'

  services:

   pclc-test:
    image: almalinux:9-minimal
    container_name: pclc-test
    restart: always
    entrypoint: /bin/bash
    network_mode: bridge

**Comment by srbala** [comment]
@perry-amsterdam this is expected based on your input yaml. BTW, formated would be nice.

Bash command is a simple exec, it completes after executes it. Since you have restart set `yes`, it goes into loop.

```yaml
version: "3.1"

services:
  pclc-test:
    image: almalinux:9-minimal
    container_name: pclc-test
    restart: always
    entrypoint: /bin/bash
    network_mode: bridge
```
